### ISSUE TITLE
Verilator 5 support

### ISSUE THREAD

**Issue by RickLuiken** [KULeuven-MICAS/snitch_cluster#65]
Currently, using verilator 5 results in an error when following the [tutorial](https://kuleuven-micas.github.io/snitch_cluster/ug/tutorial.html). In verilator 5, timing support was added, so if there is a delay somewhere, we need add either the --timing or --no-timing flag. No timing will result in the same behavior as previously.

Next, a new error shows up: undefined references to VlThreadpool. This can also be fixed easily, by adding verilated_threads.o to the targets. This makes me wonder though, why are the cpp files not compiled using the verilator command? This way we can make use of the automatically generated makefile, which would have prevented this issue.

I can create a PR for adding support, let me know what you think about compiling everything with the verilator command.

**Comment by JosseVanDelm** [comment]
Hi @RickLuiken,

Thanks for reaching out and welcome to snax!

We are currently just following the flow as set up by our lovely colleagues and dear friends over at https://github.com/pulp-platform/snitch_cluster . In our tests, we use verilator 4.110, since this is the same version used upstream.
 It seems that they use https://github.com/pulp-platform/bender to do dependency management and script generation for many tools including verilator.

Some of us prefer debugging hardware traces in questasim, for which we can also use bender, so right now we stick to this flow.
Is there any reason you'd like to see verilator 5 support here, or in upstream snitch_cluster? I.e. do you (would we?) need the `--timing` flag? I'm no verilator expert, any insights here are very much welcome.

Hopefully this answers your question/solves your issue

**Comment by JosseVanDelm** [comment]
Hi @RickLuiken,

My main issue with adding support for a new verilator version is that we are also, rather implicitly, dependent on other projects, such as https://github.com/pulp-platform/cheshire, https://github.com/openhwgroup/cva6 and/or (?) https://github.com/pulp-platform/occamy .
Since the span of the project is quite large, we don't want to experiment with versions of different tools for all those dependencies.
> Like I said before, if you agree, I can make a PR adding support for verilator 5 (and still keeping support for verilator 4.110 of course!)

Adding optional verilator 5 support to just this part of the project also doesn't make a lot of sense to me; We try to cover as much code area in CI, which would imply a doubling our tests (they are already very large right now).

If verilator 5 support is a real must (how big are the performance improvements?) I would feel more at ease if you would make a PR in the upstream https://github.com/pulp-platform/snitch_cluster repo. The maintainers are much more aware of the other dependencies, and then everybody gets the improvements (we try to follow their changes every once in a while). I see no problem in updating the version of verilator on the RTL here if the version change is introduced there.

Otherwise I'm afraid you'll have to stick to 4.110 for now! Sorry!

**Comment by RickLuiken** [comment]
Thanks for the response, I have opened an issue in the upstream repo and will continue the discussion there!

**Comment by JosseVanDelm** [comment]
Very nice! I will close this issue now, feel free to reopen later as necessary.
